const colors = require("tailwindcss/colors");
module.exports = {
	content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
	important: "#__next",
	theme: {
		letterSpacing: {
			wide: ".01em",
			wider: ".05em",
			widest: ".5em",
		},
		height: {
			sm: "8px",
			md: "16px",
			lg: "24px",
			xl: "600px",
		},
		screens: {
			sm: "480px",
			md: "1024px",
			lg: "1080px",
			xl: "1440px",
		},
		colors: {
			transparent: "transparent",
			current: "currentColor",
			green: colors.green,
			black: colors.black,
			white: colors.white,
			gray: colors.gray,
			bluegray: colors.slate,
			indigo: colors.indigo,
			red: colors.rose,
			yellow: colors.amber,
			orange: colors.orange,
			blue: colors.blue,
			lime: colors.lime,
			brand: {
				1: "#FCF3E0",
				2: "#081132",
				3: "#575469",
				4: "#614A71",
				5: "#777777",
				6: "#1D1C27",
			},
		},
		fontFamily: {},
		fontSize: {
			xs: ".75rem",
			sm: ".875rem",
			tiny: ".875rem",
			base: "1rem",
			lg: "1.125rem",
			xl: "1.25rem",
			"2xl": "1.5rem",
			"3xl": "1.875rem",
			"4xl": "2.25rem",
			"5xl": "3rem",
			"6xl": "4rem",
			"7xl": "5rem",
			"8xl": "7rem",
			"9xl": "9rem",
			"10xl": "12rem",
		},
		extend: {},
	},
	plugins: [],
};
