# Generated by Django 4.0.3 on 2022-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.URLField(verbose_name='First Project Screenshot')),
                ('img2', models.URLField(verbose_name='Second Project Screenshot')),
                ('img3', models.URLField(verbose_name='Third Project Screenshot')),
                ('title', models.CharField(max_length=100, verbose_name='Projcet Title')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Project Description')),
                ('liveLink', models.URLField(verbose_name='Project Live Link')),
                ('gitLink', models.URLField(verbose_name='Github Live Link')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
